name: Run Cypress tests
on:
  pull_request:
    branches: ["main"]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # install dependencies, cache them correctly
        # and run cypress
      - name: Install Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: Build
        run: |
          npm install --global yarn
          cd github-action
          yarn

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: yarn dev
          build: yarn build
          project: ./github-action
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
